        !COMPILER-GENERATED INTERFACE MODULE: Mon May 28 09:46:38 2012
        MODULE MIXING__genmod
          INTERFACE 
            SUBROUTINE MIXING(MAXME,IREAD)
              INTEGER(KIND=4) :: MAXME
              INTEGER(KIND=4) :: IREAD
            END SUBROUTINE MIXING
          END INTERFACE 
        END MODULE MIXING__genmod
